DomadoV/DomadoV/App/ContentView.swift, DomadoV/DomadoV/Coordinator/AppCoordinator .swift, DomadoV/DomadoV/Coordinator/AppView.swift, DomadoV/DomadoV/Coordinator/RideEvent.swift, DomadoV/DomadoV/View/RideDetailView.swift, DomadoV/DomadoV/View/RideHistoryCell.swift, DomadoV/DomadoV/View/RideHistoryView.swift, DomadoV/DomadoV/View/RidePreparationView.swift, DomadoV/DomadoV/View/RideSummaryView.swift, DomadoV/DomadoV/ViewModel/RideHistoryViewModel.swift, DomadoV/DomadoV/ViewModel/RidePreparationViewModel.swift, DomadoV/DomadoV/ViewModel/RideSummaryViewModel.swift
```mermaid
graph TD
A[ContentView] -->|Uses| B[AppCoordinator]
B -->|Manages| C[currentView]
B -->|Subscribes to| D[RideEventPublishable]
D -->|Implemented by| E[RidePreparationViewModel]
D -->|Implemented by| F[ActiveRideViewModel]
D -->|Implemented by| G[PauseRideViewModel]
D -->|Implemented by| H[RideSummaryViewModel]
D -->|Implemented by| N[RideHistoryViewModel]
E -->|Sends didStartRide/didRequestHistory| I[RideEvent]
F -->|Sends didPauseRide| I
G -->|Sends didResumeRide/didFinishRide| I
H -->|Sends didDismissSummary| I
N -->|Sends didReturnToPreparation| I
I -->|Triggers| B
C -->|Shows| J[RidePreparationView]
C -->|Shows| K[ActiveRideView]
C -->|Shows| L[PauseRideView]
C -->|Shows| M[RideSummaryView]
C -->|Shows| O[RideHistoryView]
J -.->|User Action| E
K -.->|User Action| F
L …
```
=> [feat] 화면 이동 로직 구현 

DomadoV/DomadoV/Assets.xcassets/ElectricBlue.colorset/Contents.json, DomadoV/DomadoV/Assets.xcassets/ElectricBlueDark.colorset/Contents.json, DomadoV/DomadoV/Assets.xcassets/LavenderPurple.colorset/Contents.json, DomadoV/DomadoV/Assets.xcassets/LavenderPurpleDark.colorset/Contents.json, DomadoV/DomadoV/Assets.xcassets/MidnightCharcoal.colorset/Contents.json, DomadoV/DomadoV/Assets.xcassets/SunsetOrange.colorset/Contents.json, DomadoV/DomadoV/Assets.xcassets/SunsetOrangeDark.colorset/Contents.json
- 디자인 시스템에 명시되어 있는 ColorSet을 추가했습니다. 
- 지정된 각 Color에 .문법을 통해 쉽게 접근 할 수 있습니다. 
> ~~Dark Color는 다크모드일 때만 별도로 지정되어 있는 색으로 라이트모드일때는 ~~ Color와 동일한 색을 가집니다.
=> [chore] ColorSet Asset 추가

DomadoV/DomadoV/Model/RideSession.swift, DomadoV/DomadoV/Service/LocationManager.swift
1. LocationManager 클래스:
- `authorizationPublisher`를 추가하여 위치 권한 상태 변경사항을 발행
2. RideSession 클래스:
- 주행 관련 상태 및  위치 권한과 관련된 프로퍼티 추가 (state, authorizationStatus, locationPermissionDenied)
- 주행 세션 관리를 위한 메서드 구현 (prepare(), start(), pause(), resume(), stop())
- 위치 업데이트 처리 로직 구현 (handleLocationUpdate(), handleNewLocation())
- 권한 상태 구독 및 관리 로직 추가
1. 위치 권한 관리 개선:
- 사용자의 위치 권한 상태를 실시간으로 추적하고 대응하기 위해
- 앱의 다른 부분에서 권한 상태 변경에 쉽게 반응할 수 있도록 함
2. 주행 세션 관리 기능 구현:
- 사용자의 주행 데이터를 정확하게 추적하고 관리하기 위해
- 주행 시작, 일시 정지, 재개, 종료 등의 기능을 제공하여 사용자 경험 향상
- 지도상의 사용자 위치정보를 표시하기 위해 
- 실시간 위치 데이터를 기반으로 속도, 거리 등의 정보를 계산하고 업데이트하기 위해
1. LocationManager 테스트:
- 앱 실행 시 초기 권한 상태 확인
- 권한 요청 후 상태 변경 확인
- 권한 변경 시 `authorizationPublisher`를 통해 새로운 상태가 발행되는지 확인
2. RideSession 테스트:
- `prepare()` 메서드 호출 후 권한 상태에 따른 동작 확인
- 주행 시작, 일시 정지, 재개, …
=> [feat] LocationManager 권한 발행자 및 RideSession 메서드 추가

DomadoV/DomadoV/App/ContentView.swift, DomadoV/DomadoV/Coordinator/AppCoordinator .swift, DomadoV/DomadoV/Model/RideSession.swift, DomadoV/DomadoV/View/ActiveRideView.swift, DomadoV/DomadoV/View/PauseRideView.swift, DomadoV/DomadoV/View/RidePreparationView.swift, DomadoV/DomadoV/View/RideSummaryView.swift, DomadoV/DomadoV/ViewModel/ActiveRideViewModel.swift, DomadoV/DomadoV/ViewModel/PauseRideViewModel.swift, DomadoV/DomadoV/ViewModel/RidePreparationViewModel.swift, DomadoV/DomadoV/ViewModel/RideSummaryViewModel.swift
- `AppCoordinator`에 `RideSession` 프로퍼티 추가 
- `RidePreparationViewModel`, `PauseRideViewModel`, `ActiveRideViewModel`, `RideSummaryViewModel` 에 `RideSesion` 프로퍼티 및 생성자 추가 
- `RideSession`의 `targetSpeedRange` 기본값 할당 및 생성자에서 제거 
-`ContentView`에서 `RideSession` 초기화 및 각 ViewModel에 주입  
- `AppCoordinator`에서 `RideSession`을 관리하게 함으로써 하나의 주행에 대한 일관된 기록이 가능합니다. 
- `ContentView`에서 `AppCoordinator`로부터 `RideSession`을 받아 각 ViewModel을 초기화하면서 주행시 각 화면에 대한 로직을 한 곳에 관리 가능합니다. 
- `RideSession`의 `targetSpeedRange`에 기본값을 줌으로써 주행 시작전 사용자가 설정한 속도 범위로 `RideSession`을 업데이트 해주어야합니다.
=> [feat] RideSession 관리 Flow 구현

DomadoV/DomadoV.xcodeproj/project.pbxproj, DomadoV/DomadoV/Model/RideSession.swift, DomadoV/DomadoV/View/RidePreparationView.swift, DomadoV/DomadoV/ViewModel/RidePreparationViewModel.swift
- 위치 권한 요청 메시지 추가 
- `RideSession`에서 사용자 현재 위치 프로퍼티 제거 
- `RidePreparationViewModel `에서 위치 권한 체크 및 alert 동작을 위한 프로퍼티 추가 
- `RidePreparationView`에서 MapKit을 이용 사용자 현재 위치 표시
- `onAppear`를 이용해 주행뷰에서 사용자 위치권한 체크 
- `alert`를 이용해 위치 권한 없을시 시스템 설정으로 위치 권한 설정 
- 주행 시작전 사용자의 위치 권한을 확인합니다.
- 사용자의 현재 위치를 지도상에 표시함으로써 사용자가 기기의 GPS 상태에 대한 인지 하도록 합니다. 
- viewModel에 MapKit에 대한 의존성을 제거하기 위해 `position` 프로퍼티는 View에서 직접 관리하도록 했습니다. 
-  iOS 17이상을 지원하므로 MapKit을 이용 사용자 현재 위치를 표시합니다. 따라서 사용자의 현재 위치 정보를 직접 관리하지 않습니다. ( RideSession 및 PrearationViewModel에서 사용자 현재 위치 발행 및 구독 흐름을 제거했습니다. )
- 향후 17 미만 버전에 대한 지원이 필요한 경우 8d5a026 커밋을 참조하여 사용자 위치정보를 직접 관리할 수 있습니다.
=> [feat] 주행 준비화면 동작 구현 

DomadoV/DomadoV/Model/RideSession.swift, DomadoV/DomadoV/View/ActiveRideView.swift, DomadoV/DomadoV/ViewModel/ActiveRideViewModel.swift, DomadoV/DomadoV/ViewModel/PauseRideViewModel.swift, DomadoV/DomadoV/ViewModel/RidePreparationViewModel.swift
-`RideSession`에 타이머 프로퍼티 및 타이머 동작 메서드를 추가했습니다.  
-`RideSession`에 `currentSpeed`의 단위 변환 및 max 추가 
- `ActiveRideViewModel`에서 `RideSession` 프로퍼티 구독 및 발행  
- `ActiveView`에서 vm 로부터 발행된 프로퍼티 값 확인  
- ViewModel의 화면 이동로직 (send) 이후의 `RideSession`의 주행 관리 메서드 호출 추가 
- 타이머를 통해 주행 시작 후 사용자 위치정보 변화가 없어도( 사용자가 멈춘 경우) 주행 시간 업데이트를 가능하도록 합니다. 
- m/s 를 km/h 단위로 변경하여 일반적인 속도계앱과 같은 단위를 제공합니다. 
- `RideSession`에서 관리되고 있는 주행 정보를 주행 중 화면에 표시합니다. 
- 화면이동으로 바뀐 화면에 대응하는 `RideSession`의 업데이트를 관리합니다. 
-  현재 실내에서 GPS 드리프트 현상으로 이동하지 않아도 거리가 증가하는 현상이 있습니다. 향후 이것에 대한 최적화 작업이 필요합니다.
=> [feat] 주행중 화면 업데이트 및 동작 로직 구현 

DomadoV/DomadoV/Model/RideSession.swift, DomadoV/DomadoV/Service/LocationManager.swift
- `calculateDistance` 메서드에서 `toLocation` 변수 계산시 `from`경도를 사용하던 부분을 `to` 경도로 수정하였습니다.
- `pause` 메서드 호출시 `currentSpeed`를 0으로 업데이트 합니다. 
- `locationManager`에 사용자 위치 업데이트시 수평정확도를 통해 위치 데이터를 필터링합니다. 
- `handleNewLocation`에서 속도계산시 저역 통과 필터를 적용했습니다.
- `puase`시 `previousLocation` 값을 제거합니다.
- 현재속도를 필터링된 값을 사용합니다. 
- `LocationManager`에서 `CLLocationManager` 에 대한 설정을 변경했습니다. (distanceFilter, activityType, pausesLocationUpdatesAutomatically)
- 위치 업데이트가 없는 duration을 확인해서 속도를 업데이트하는 로직을 추가했습니다.
- 위치 업데이트가 없을 시에 하는 속도 업데이트가 점진적으로 이루어지도록 했습니다. 
- 사용자의 현재 속도를 명확히 표시하고 급격한 속도변화를 줄여 사용자가 속도를 편하게 확인할 수 있도록 합니다. 
- `LocationManager`으로부터의 받은 위치 데이터 속도값을 바로 사용하지 않고 필터링하여 노이즈를 줄입니다. 
- `distanceFilter`를 적용해 일정 거리이상 움직이지 않으면 위치값을 발행하지 않도록 합니다. 
- 주행시간 업데이트시 사용하던 타이머를 사용, 마지막 속도 업데이트 시점을 체크하여 위치 데이터가 발행되지 않아도 속도를 …
=> [enh] 속도 측정 기능 개선 

DomadoV/DomadoV/Model/RideSession.swift, DomadoV/DomadoV/Service/LocationManager.swift
- `speedCheckInterval` 1.8로 변경 
- 점진적 속도 감속 로직 삭제 
- `LocationManager` 위치 정확도 최고로 설정 
- `LocationManager` 수평 정확도 범위 넓힘 
- 점진적 감속로직을 사용하니 정지시 정지 상태에 대한 화면 피드벡이 너무 느리게 반영되는 현상을 관찰했습니다. 
- 따라서 점진적 감속 로직을 제거하여 정지상태가 빠르게 화면에 반영될 수 있도록 하였습니다. 
- 속도 갱신 flow
1. **조건**:`distanceFilter = 2 ` 이상의 위치 변화가 생김 & 해당 위치 변화의 수평정확도가 20 이내로 들어오는 경우, `LocationManager`로부터 현재 위치 발행 
2. 현재 위치가 발행시 `RideSession`에서 발행된 위치에 대하여 `handleNewLocation`을 통해 현재 속도 계산 및 화면에 반영 
3.  조건을 통과하지 않은 경우 (사용자가 `distanceFilter`이상 움직이지 않거나 현재 위치 신뢰성이 떨어지는 경우 )가 지정한 시간 `speedCheckInterval` 동안 이루어지면  움직임이 없는 것으로 판단`checkAndUpdateSpeed` 메서드가 실행되어 현재 속도를 0으로 만듭니다. 
- 조정시 고려사항 
1.  `speedCheckInterval`를 늘려 다음 위치데이터 발행을 더 기다리거나 아니면 줄여 정지 상태 판단을 빠르게 할 수 있습니다. 
2. `distanceFilter`를 짧게 만들어 위치 발행 주기를 더 짧게 만들 수 있습니다. 
3. 측정하려는 활동의 특성을 고려하여 위치 …
=> [enh] 정지시 속도 반영 개선 

DomadoV/DomadoV/Persistent/CoreDataManager.swift
- CoreDataManager 싱글톤 클래스 구현
- NSPersistentContainer를 사용한 Core Data 스택 초기화
- 메인 컨텍스트 및 파생 컨텍스트 저장 로직 구현
- 컨텍스트 계층 구조를 고려한 저장 메커니즘 구현
- 앱 전체에서 일관된 Core Data 스택 사용을 위해
- 데이터 관리 로직의 중앙화로 코드 중복 감소
- 멀티 스레딩 환경에서의 안전한 데이터 조작을 위해
- UI 반응성 향상 및 백그라운드 작업 지원
`NSPersistentContainer(name: "PacepalModel")`에서 사용하고 있는 PacepalModel에 대한 dataModel을 만들어야합니다.
=> [feat] CoreDataManager 구현

DomadoV/DomadoV/Model/RideSession.swift, DomadoV/DomadoV/View/RideSummaryView.swift, DomadoV/DomadoV/ViewModel/RideSummaryViewModel.swift
- `RideSession`의 평균속도를 연산 프로퍼티로 변경하였습니다. 
- `RideSession`이 관리하는 주행정보들을 `RideSummary` 인스턴스로 반환하는 `generateRideSummary` 메서드를 구현하였습니다.
- `RideSummaryViewModel`에 `RideSession`의 `generateRideSummary` 호출하여 `RideSummary`를 얻어 이를 화면에 보여줍니다. 
- 속도 구간별 시간의 경우, `RideSummary.speedDistribution`의 각 속도 구간별 시간의 비율대로 전체 주행 시간을 나누어 반환하도로 하였습니다. 
- `RideSummaryView`  등장시 `vm.getSummary` 메서드를 호출하여 RideSession으로부터 `RideSummaryViewModel`로 주행정보를 가져옵니다. 
- `RideSummaryView`는 `RideSummary`를 통해 필요한 정보를 화면에 표시합니다. 
종료된 주행에 대한 사용자에게 보여줍니다. 
- 현재 뷰는 필요한 정보만 표시되고 디자인이 반영되지 않은 상태입니다. 
- 거리나 시간 단위를 포멧팅하는 별도의 Extension 이 필요해보입니다.
=> [feat] 주행 요약 기능 구현 

DomadoV/DomadoV/Model/RideRecord.swift, DomadoV/DomadoV/Service/RideHistoryManager.swift, DomadoV/DomadoV/ViewModel/RideHistoryViewModel.swift
- `RideRecord` DTO 추가
- `RideHistoryManager`의 fetch 메서드 `RideRecord` 반환 
- `RideHistoryViewModel` 의 `RideRecord` 모델 주행기록 관리 
- 엔티티를 `RideRecord`로 변환하여 비즈니스 계층에 노출하지 않습니다. 
- `RideHistoryViewModel` 에서  코어데이터로부터 저장된 주행기록을 가져옵니다.
=> [feat] RideHistoryViewModel 주행기록 fetch 로직 추가 

DomadoV/DomadoV/View/PauseRideView.swift
- alert의 색상을 gray로 변경하였습니다. 
- alert을 구성하는 Content를 x 버튼 터치 영역을 확장했습니다. 
- `isLongPressing ` 프로퍼티를 추가했습니다. 
- `simultaneousGesture` 와 `LongPressGesture `를 이용해 짧은 탭과 긴 탭을 구분합니다. 
- 짧은 탭에 대해서는 알림이 긴 탭에 대해서는 주행 정지가 가능하도록 변경합니다.
=> [fix] 롱프레스를 통한 주행 정지

DomadoV/DomadoV/Persistent/PacepalModel.xcdatamodeld/PacepalModel.xcdatamodel/contents
- 주행 기록 엔티티의 routeData 속성을 옵셔널로 변경했습니다. 
- 주행기록이 존재하지 않아도 주행기록에 대한 저장이 일단 가능하게 합니다. 
- 주행 경로 속성을 사용시 해당 옵셔널 언래핑하는 과정이 요구됩니다.
=> [bug] 경로 데이터 없을시 저장 실패 

DomadoV/DomadoV/View/Component/RideRouteMapView.swift
1. `RideRouteMapView` 구조체 구현:
- 주어진 경로를 지도에 표시하는 SwiftUI 뷰 생성
- 경로가 비어있을 때와 있을 때의 다른 뷰 표시 로직 구현
2. 지도 초기화 및 경로 표시:
- `MapKit`을 사용하여 지도 뷰 구현
- 주어진 좌표 배열을 기반으로 경로를 `MapPolyline`으로 표시
3. 동적 지도 영역 설정:
- 경로의 모든 좌표를 포함하는 최적의 지도 영역을 계산하는 로직 구현
4. 프리뷰 제공:
- 경로가 있는 경우와 없는 경우에 대한 프리뷰 구현
1. 사용자 경험 향상:
- 라이드 루트를 시각적으로 표시하여 사용자가 경로를 쉽게 이해할 수 있도록 함
2. 동적 데이터 처리:
- 다양한 경로 데이터에 대응할 수 있는 유연한 뷰 구현
3. 성능 최적화:
- 경로에 따라 자동으로 지도 영역을 조정하여 사용자가 수동으로 조작할 필요 없이 전체 경로를 한눈에 볼 수 있도록 함
1. 코드 구조 설명:
- `RideRouteMapView` 구조체는 `route` 파라미터를 받아 초기화됩니다. 이 파라미터는 `CLLocationCoordinate2D` 배열로, 라이드 경로의 좌표들을 나타냅니다.
- `init` 메서드에서는 초기 지도 위치를 설정합니다. 경로가 있으면 첫 번째 좌표를 중심으로, 없으면 서울의 좌표를 기본값으로 사용합니다.
- `body` 프로퍼티에서는 경로의 유무에 따라 다른 뷰를 표시합니다. 경로가 없으면 "경로 없음" 텍스트를, 있으면 지도와 경로를 표시합니다.
- `setRegionToFitRoute()` 메서드는 모든 경로 좌표를 포함하는 최적의 지도 …
=> [feat] 지도상 주행 경로를 표시합니다. 

DomadoV/DomadoV/Extension/Extension+Date.swift, DomadoV/DomadoV/Extension/Extension+Double.swift, DomadoV/DomadoV/Extension/Extension+TimeInterval.swift, DomadoV/DomadoV/Model/RideRecord.swift, DomadoV/DomadoV/Model/SpeedDistribution.swift, DomadoV/DomadoV/Service/RideHistoryManager.swift, DomadoV/DomadoV/View/Component/RideRouteMapView.swift, DomadoV/DomadoV/View/Component/SpeedDistributionView.swift, DomadoV/DomadoV/View/RideDetailView.swift, DomadoV/DomadoV/View/RideHistoryCell.swift, DomadoV/DomadoV/View/RideHistoryView.swift, DomadoV/DomadoV/View/RideSummaryView.swift, DomadoV/DomadoV/ViewModel/RideHistoryViewModel.swift, DomadoV/DomadoV/ViewModel/RideSummaryViewModel.swift
- 날짜 포멧팅을 위한 Date Extension 추가
- 거리 포멧팅을 위한 Double Extension 추가
- 시간 포멧팅을 위한 TimeInterval Extension 추가
- RideRecord 구조체 Hashable 채택 및 평균속도 계산시 guard 로 발산하는 경우 예방 
- SpeedDistribution에 구간별 속도 비율 계산 static 메서드 추가
- RideSummaryViewModel에서 속도 분포를 SpeedDistribution의 static 메서드를 통해 얻도록 함 
- RideHistoryViewModel에 주행기록 삭제 메서드 추가 
- SpeedDistributionView 속도분포 뷰 컴포넌트 추가 
- RideRouteMapView 시작위치, 도착위치 표시및 경로 끓긴 경우에 대한 처리 
- Ride 엔티티 fetch시 최근 주행순으로 가져오기
- RideSummaryView에서 SpeedDistributionView 사용 
- 주행기록 View에 RideRecord 를 사용하는 방식으로 변경 
사용자에게 주행기록을 보여줍니다 .
- 뷰와 관련해서 날짜, 거리, 시간에 대해 포멧팅 extension을 활용하도록 바꾸었습니다. 
- 주행기록 뷰에 대해 상당부분이 바뀌어 기존 작업 상황과 충돌이 생길수도 있습니다.
=> [feat] 실제 저장된 주행기록 보여주기 

DomadoV/DomadoV/Model/RideSession.swift, DomadoV/DomadoV/View/PauseRideView.swift, DomadoV/DomadoV/ViewModel/PauseRideViewModel.swift
- PuaseRideView에서 viewModel로부터 정보를 받아와 표시하도록 했습니다. 
- viewModel에 거리와 주행 시간에 대한 프로퍼티를 추가한뒤, vm 초기화시 RideSession으로부터 해당 값을 받아오도록 하였습니다.
- viewModel에 타이머를 추가하여 현재 세션의 휴식시간을 표시합니다. 
- RideSession의 전체 휴식시간 계산로직을 수정하였습니다. 
- 사용자에게 현재까지의 주행시간, 주행거리를 표시해주고 현재 세션의 경과 휴식시간을 보여줍니다. 
- 기존의 휴식시간 로직은 pause가 다시 resume될때만 현재 휴식시간을 더했기 때문에 마지막 휴식세션의 휴식시간이 계산에 포함되지 않는 현상이 있어서 전체 휴식시간을 연산프로퍼티로 변경한후 전체 휴식시간은 마지막 휴식시간까지 고려하여 계산하도록 하였습니다. 
close #43
=> [feat] 휴식 화면 실제 정보 표시 

DomadoV/DomadoV/App/ContentView.swift, DomadoV/DomadoV/Coordinator/AppCoordinator .swift, DomadoV/DomadoV/Coordinator/AppView.swift, DomadoV/DomadoV/Coordinator/RideEvent.swift, DomadoV/DomadoV/Model/RideSession.swift, DomadoV/DomadoV/View/CountdownView.swift, DomadoV/DomadoV/ViewModel/CountdonwViewModel.swift, DomadoV/DomadoV/ViewModel/RidePreparationViewModel.swift
- `AppView`와 `RideEvent`에 Countdown 화면에 대한 케이스를 추가했습니다. 
- `RideSession`의 `start`메서드에서 속도범위 설정을 하는 부분을 별도의 메서드 `setTargetSpeedRange`로 분리했습니다. 
- `RidePreparationViewModel`에서 `startRide` 호출시 `RideSession의 `setTargetSpeedRange`메서드를 호출하여 속도 범위를 설정한뒤 카운트다운뷰로 이동합니다. 
- `CountdownViewModel`에서는 화면에 보여지는 남은 시간에 대한 카운트를 Timer를 통해 관리하고 카운팅이 완료되면 RideSession의 `start`메서드를 호출하여 주행을 시작하고 주행화면으로 이동합니다.  
- `CountdownView`는 현재 남은시간을 숫자와 원의 남은 부분을 통해 시각적으로 보여줍니다. 
- `AppCoordinator`와 `ContentView`에서 새로 추가된 countdown 케이스에 대한 화면 전환 로직을 추가했습니다.
- 주행이 시작전 카운트다운을 통해 사용자에게 라이딩을 준비할 수 있는 시간을 제공합니다.
=> [feat] 주행시작전 카운트 다운

DomadoV/DomadoV/View/ActiveRideView.swift, DomadoV/DomadoV/ViewModel/ActiveRideViewModel.swift
- `ActiveRideView`에 여백, 폰트, 색상을 적용했습니다.
- `ActiveRideViewModel` 숫자 포맷을 `%.f` 로 변경해 소수점 없이 출력되게 설정했습니다. 
- Hi-Fi 디자인과 최대한 가까운 화면을 구현합니다.
- 속도가 표시될 때 `...`으로 나오는 상황을 방지합니다.
1. 앱을 실행하고 주행준비 화면으로 이동
2. 시작버튼을 눌러 주행화면 확인
4. 다크 모드 전환 시 UI가 적절히 변경되는지 확인
| 라이트 모드 | 다크 모드 |
<div style="display: flex; justify-content: space-around;">
</div>
- 다크모드가 적용되었으나, 속도에 따라 색상이 변경되는 부분은 구현되지 않았습니다.
=> [feat] 주행 화면 구현

DomadoV/DomadoV/View/PauseRideView.swift
- 휴식화면 버튼을 수정합니다
- 시각보정을 위해 플레이버튼 내부의 아이콘 위치를 조정합니다.
- 중지 버튼 배경을 `clear`로 변경합니다.
=> [feat] 휴식 화면 버튼 수정

DomadoV/DomadoV/Extension/Extension+TimeInterval.swift, DomadoV/DomadoV/View/Component/SpeedDistributionView.swift, DomadoV/DomadoV/View/RideSummaryView.swift
- `RideSummaryView`에 여백, 폰트, 색상을 적용했습니다.
- `SpeedDistributionView`에 디자인을 적용했습니다.
- `SpeedDistributionView`의 `contentView` 내부를 수정했습니다.
- `Extension+TimeInterval` 의 시간 단위를 영문으로 수정했습니다.
- Hi-Fi 디자인과 최대한 가까운 화면을 구현합니다.
- 코드를 약간 간결하게 만듭니다.
1. 앱을 실행하고 주행준비 화면으로 이동
2. 시작버튼을 눌러 주행화면으로 이동
3. 일시정지 버튼을 눌러 휴식화면으로 이동
4. 중지 버튼을 길게 눌러 주행 완료 화면 확인
5. 컴포넌트가 적절히 배치되었는지 확인
7. 다크 모드 전환 시 UI가 적절히 변경되는지 확인
<div style="display: flex; justify-content: space-around;">
</div>
- padding 값 외에 폰트의 내부 여백이 더해져 간격이 벌어진 것을 확인했습니다. 추후 수정 필요.
=> [feat] 주행완료 화면 구현

DomadoV/DomadoV/View/Component/ArcRangeSlider.swift
- ArcRangeSlider를 구현하였습니다. 
- 주행준비 화면에서 사용자가 자신이 원하는 속도범위를 선택할 수 있도록 합니다.
- 준비화면의 뷰모델로부터 @Published 되는 closedRange<Double> 값을 해당 슬라이더의 @Binding 값과 연결합니다.
=> [feat] 호모양 범위 슬라이더 구현 

DomadoV/DomadoV/View/ActiveRideView.swift, DomadoV/DomadoV/ViewModel/ActiveRideViewModel.swift
- `ActiveRideViewModel`에  `targetSpeedRange`를 프로퍼티로 추가하였습니다. 이 프로퍼티는 현재 속도(`currentSpeed`)가 변화할 때마다 속도 범위를 비교하기 위해 사용됩니다.
- `rideSession`에 있는 목표 속도 범위(`targetSpeedRange`)를 가져와 `targetSpeedRange` 프로퍼티에 할당해 초기화해줍니다.
- `ActiveRideViewModel`에 `backgroundColor` 프로퍼티를 추가하고 `@Published`속성을 붙여, 값이 변할 때마다 주행 화면에 반영되도록 합니다.
- `currentSpeed`가 변경될 때 마다 `changeBackground()`를 호출하여 배경 색상을 업데이트합니다. 
- `changeBackground()` 에서는 `currentSpeed`와 `targetSpeedRange`를 비교해서 `backgroundColor`를 변경하는 로직을 구현하였습니다. 이를 통해 주행 중 목표 속도 범위에 들어와있는지 여부를 시각적으로 나타낼 수 있습니다.
사용자가 설정한 속도범위를 기준으로 현재 속도 상태를 배경색으로 보여줍니다.
1. 앱을 실행하고 주행준비화면으로 이동
2. 속도 범위 설정 후, 라이딩 시작 버튼을 눌러 **주행 화면**으로 이동
4. 설정한 속도 범위를 기준으로 배경색이 적절히 변화되는지 확인
5. 다크 모드 전환 시 UI가 적절히 변경되는지 확인
<div style="display: flex; justify-content: space-around;">
</div>
- 다크모드를 위해 …
=> [feat] 주행 화면 배경 색상 변경 적용
